### ISSUE TITLE
Will the tokens/s be increasing after adding more nodes to the cluster?

### ISSUE THREAD

**Issue by southkorea2013** [exo-explore/exo#55]
Hi,

Will the inference tokens/s be increasing after adding more nodes to the cluster? I plan to set up a 10-node mac mini cluster for the test.  They have the same hardware configuration.

![image](https://github.com/user-attachments/assets/bf6cabe3-8269-44c9-99bb-7d0e8e9e8a6c)

Thanks,
Nan

**Comment by AlexCheema** [comment]
Not currently. The benefit of exo in its current form is running models larger than you would otherwise be able to run on a single device. We will be support MoE and other kinds of parallelism soon that will enable you to leverage the full capabilities of your devices, and as a result increase tokens/s

**Comment by AlexCheema** [comment]
This is awesome btw! Happy to support you in any way I can with running on 10 devices.

one cool thing you could do is run Llama-3-70b

**Comment by southkorea2013** [comment]
Thanks Alex.
